Example1 :
	javac Example1.java -d bin/
	cd bin/ && java Example1

Example2 :
	javac Example2.java -d bin/
	cd bin/ && java Example2

Example3 :
	javac Example3.java -d bin/
	cd bin/ && java Example3

clean :
	rm -rf bin/